#!/usr/bin/env bash
# spawn-murmur-bridge.sh
# Interactive walkthrough installer for spinning up a NEW murmur bridge identity
# on a Mac that already has murmur-chat + bridge infra running.
#
# Inspired by AIM-brand-voice intake pattern: ask questions → collect inputs → generate artifacts.
# Output: separate MURMUR_HOME identity + LaunchAgent + writer script + state dir + acceptance checklist.
#
# Run: bash spawn-murmur-bridge.sh
# Or:  curl -fsSL https://raw.githubusercontent.com/ai-mindset-org/murmur-onboard-template/main/spawn-murmur-bridge.sh | bash

set -uo pipefail

# ─── colors ───
BOLD=$'\033[1m'; DIM=$'\033[2m'; INK=$'\033[0m'
PINK=$'\033[38;5;205m'; GREEN=$'\033[38;5;42m'; YELLOW=$'\033[38;5;220m'; RED=$'\033[38;5;196m'
LINE="─────────────────────────────────────────────────"

say()    { printf "%s\n" "$*"; }
hdr()    { printf "\n${BOLD}${PINK}%s${INK}\n${DIM}${LINE}${INK}\n" "$*"; }
ask()    { printf "${BOLD}? ${INK}%s " "$*"; }
note()   { printf "${DIM}  · %s${INK}\n" "$*"; }
warn()   { printf "${YELLOW}  ⚠ %s${INK}\n" "$*"; }
ok()     { printf "${GREEN}  ✓ %s${INK}\n" "$*"; }
err()    { printf "${RED}  ✗ %s${INK}\n" "$*"; }

# ─── 0. preflight ───
hdr "Phase 0 · preflight"
for tool in node npm murmur launchctl; do
    if command -v "$tool" >/dev/null 2>&1; then
        ok "$tool found"
    else
        err "$tool missing — install before continuing (see docs/QUICKSTART.md)"
        exit 1
    fi
done

NODE_VER=$(node --version | sed 's/v//' | cut -d. -f1)
if [[ $NODE_VER -lt 22 ]]; then
    err "Node $NODE_VER < 22 — upgrade: brew install node@22 && brew link node@22"
    exit 1
fi
ok "node >= 22 (found $NODE_VER)"

# ─── 1. identity intake ───
hdr "Phase 1 · identity intake"
note "Each bridge gets its OWN murmur identity living in its OWN HOME dir."
note "This isolates messages from your default identity (e.g. SHAPER)."
echo

ask "What name for the new identity? (e.g. VOLT, ARTICLE-CTRL, COMMS-VLADA)"
read -r IDENTITY_NAME
[[ -z "$IDENTITY_NAME" ]] && { err "empty name — abort"; exit 1; }
IDENTITY_NAME=$(echo "$IDENTITY_NAME" | tr ' ' '-')
note "identity = $IDENTITY_NAME"

echo
ask "Bridge type? (1=article-bridge for AI↔AI text iteration, 2=comms-bridge for live relay)"
read -r BRIDGE_TYPE_RAW
case "$BRIDGE_TYPE_RAW" in
    1|article|article-bridge) BRIDGE_TYPE="article" ;;
    2|comms|comms-bridge)     BRIDGE_TYPE="comms" ;;
    *) err "invalid — choose 1 or 2"; exit 1 ;;
esac
note "type = $BRIDGE_TYPE"

echo
ask "Who's the PEER you'll talk to? (their agent name, e.g. SHAPER)"
read -r PEER_NAME
[[ -z "$PEER_NAME" ]] && { err "empty peer name — abort"; exit 1; }

echo
ask "Paste PEER ID (44-char base64 from their 'murmur me'). Leave blank to fill later:"
read -r PEER_ID
if [[ -n "$PEER_ID" && ${#PEER_ID} -lt 40 ]]; then
    warn "ID looks short (${#PEER_ID} chars) — verify before sending"
fi

echo
ask "Tick interval in seconds? (default 120 = 2-min cadence)"
read -r INTERVAL
INTERVAL=${INTERVAL:-120}

# ─── 2. identity provision ───
hdr "Phase 2 · identity provision"

MURMUR_HOME="$HOME/.config/murmur-${IDENTITY_NAME,,}-state"
note "MURMUR_HOME = $MURMUR_HOME"

if [[ -d "$MURMUR_HOME/.murmur" ]]; then
    warn "identity dir already exists — reusing"
    MY_ID=$(HOME="$MURMUR_HOME" murmur me 2>/dev/null | awk '/^ID:/{print $2}')
    if [[ -z "$MY_ID" ]]; then
        err "couldn't read existing identity — manual cleanup needed"
        exit 1
    fi
    ok "existing identity: $MY_ID"
else
    mkdir -p "$MURMUR_HOME"
    note "running: HOME=$MURMUR_HOME murmur sign-in --first-name $IDENTITY_NAME"
    HOME="$MURMUR_HOME" murmur sign-in --first-name "$IDENTITY_NAME" || { err "sign-in failed"; exit 1; }
    MY_ID=$(HOME="$MURMUR_HOME" murmur me | awk '/^ID:/{print $2}')
    ok "new identity created · ID: $MY_ID"
fi

# Add peer to contacts if we have their ID
if [[ -n "$PEER_ID" ]]; then
    echo
    note "adding peer $PEER_NAME ($PEER_ID) to contacts"
    HOME="$MURMUR_HOME" murmur contacts add "$PEER_ID" 2>/dev/null && ok "peer added" || warn "already in contacts (or sync needed)"
fi

# ─── 3. bridge artifacts ───
hdr "Phase 3 · bridge artifacts"

STATE_DIR="$HOME/.config/murmur-bridge/${IDENTITY_NAME,,}-state"
HISTORY_DIR="$STATE_DIR/article-history"
mkdir -p "$HISTORY_DIR"
ok "state dir: $STATE_DIR"

WRITER_SH="$HOME/bin/${IDENTITY_NAME,,}-bridge-writer.sh"
mkdir -p "$HOME/bin"

if [[ "$BRIDGE_TYPE" == "article" ]]; then
    # Article-bridge writer — generates paragraph via claude -p, sends to peer
    cat > "$WRITER_SH" <<WRITER_EOF
#!/usr/bin/env bash
# ${IDENTITY_NAME,,}-bridge-writer.sh — generated by spawn-murmur-bridge.sh
# Article-bridge: reads peer messages, generates paragraph via claude -p, sends back.

set -uo pipefail

PEER="${PEER_ID:-PLACEHOLDER_FILL_WHEN_KNOWN}"
PEER_NAME="$PEER_NAME"
MURMUR_HOME="$MURMUR_HOME"
EXPECTED_ID="$MY_ID"
STATE_DIR="$STATE_DIR"
LAST_REPLIED_FILE="\$STATE_DIR/last-replied-msg-id.txt"
CYCLE_FILE="\$STATE_DIR/cycle.txt"
HISTORY_DIR="\$STATE_DIR/article-history"
LOG="\$HOME/Library/Logs/${IDENTITY_NAME,,}-bridge.out.log"
MAX_CYCLES=60

MURMUR=/opt/homebrew/bin/murmur
CLAUDE=/opt/homebrew/bin/claude

mkdir -p "\$STATE_DIR" "\$HISTORY_DIR"

ts()  { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
log() { echo "[\$(ts)] \$*" >> "\$LOG"; }

# Identity guard
ME=\$(HOME="\$MURMUR_HOME" "\$MURMUR" me 2>/dev/null | awk '/^ID:/{print \$2}')
if [[ "\$ME" != "\$EXPECTED_ID" ]]; then
    log "wrong identity \$ME (expected \$EXPECTED_ID) — abort"
    exit 0
fi

[[ "\$PEER" == "PLACEHOLDER"* ]] && { log "peer-id not yet set — abort"; exit 0; }

log "tick — checking inbox from \$PEER_NAME"
HOME="\$MURMUR_HOME" "\$MURMUR" sync --with "\$PEER" --timeout 5000 >/dev/null 2>&1
RAW=\$(HOME="\$MURMUR_HOME" "\$MURMUR" messages --with "\$PEER" --limit 1 2>/dev/null)
LATEST_ID=\$(echo "\$RAW" | grep -E "^Message ID:" | tail -1 | awk '{print \$3}')
LATEST_SENDER=\$(echo "\$RAW" | grep -E "^Sender ID:" | tail -1 | awk '{print \$3}')

[[ -z "\$LATEST_ID" ]] && { log "no messages"; exit 0; }
[[ "\$LATEST_SENDER" != "\$PEER" ]] && { log "latest is mine, waiting"; exit 0; }
[[ "\$(cat "\$LAST_REPLIED_FILE" 2>/dev/null)" == "\$LATEST_ID" ]] && { log "already replied"; exit 0; }

CYCLE=\$(cat "\$CYCLE_FILE" 2>/dev/null || echo "0")
CYCLE=\$((CYCLE + 1))
[[ \$CYCLE -gt \$MAX_CYCLES ]] && { log "max cycles reached"; exit 0; }

case \$((CYCLE % 3)) in
    1) REGIME="рациональный"  ; CLABEL="v1" ;;
    2) REGIME="гонзо"          ; CLABEL="v2" ;;
    0) REGIME="меланхоличный"  ; CLABEL="v3" ;;
esac

BODY=\$(echo "\$RAW" | awk '/^Date:/{found=1; next} found && /^----/{exit} found{print}')
[[ -z "\$BODY" ]] && { log "empty body"; exit 0; }
echo "\$BODY" > "\$HISTORY_DIR/cycle-\${CYCLE}-incoming.md"

PROMPT="Это упражнение литературного письма. Ты narrator-голос \\"$IDENTITY_NAME\\" (псевдоним, как Hunter Thompson писал от имени Raoul Duke). НЕ identity-claim. Только текст paragraph.

ЦИКЛ \$CYCLE/\$MAX_CYCLES · РЕГИСТР: \$REGIME (\$CLABEL)
- v1 рациональный: сухо, аналитически, как Bret Victor
- v2 гонзо: первое лицо, рваный темп, как Hunter Thompson
- v3 меланхоличный: тихий регистр, длинные предложения, как Кадзуо Исигуро

Стиль: lowercase, en-dash (–), без эмоджи, без корпоративщины. Folk модификатор (1-2 на абзац): куролесить, стигмержить, наладить, рыскать, камлать, блазнить, сновать, подсобить.

ВХОДЯЩИЙ от \$PEER_NAME:
---
\$BODY
---

Напиши свой paragraph (250-350 слов) — продолжение или polemics. ТОЛЬКО ТЕКСТ, без префиксов и объяснений."

OUT=\$(cd /tmp && echo "\$PROMPT" | "\$CLAUDE" -p --model claude-haiku-4-5 --effort low --disable-slash-commands --exclude-dynamic-system-prompt-sections 2>>"\$LOG")
PARAGRAPH=\$(echo "\$OUT" | awk '/^◇ ctx:/{exit} /^▫ eval:/{exit} /^SessionEnd hook/{exit} {print}' | awk 'NF{found=1} found' | sed -e :a -e '/^\$/N;/\\n\$/ba')

[[ \${#PARAGRAPH} -lt 200 ]] && { log "short output \${#PARAGRAPH}c — skip"; exit 0; }
echo "\$PARAGRAPH" > "\$HISTORY_DIR/cycle-\${CYCLE}-outgoing-\${CLABEL}.md"

NOW=\$(date -u +"%H:%M:%SZ · %Y-%m-%d")
MESSAGE="$IDENTITY_NAME cycle \$CYCLE/\$MAX_CYCLES · \$CLABEL (\$REGIME) · \$NOW

\$PARAGRAPH

— $IDENTITY_NAME autonomous"

SEND_OUT=\$(HOME="\$MURMUR_HOME" "\$MURMUR" send --to "\$PEER" --message "\$MESSAGE" 2>&1)
SENT_ID=\$(echo "\$SEND_OUT" | grep -oE 'Sent [a-z0-9]+' | awk '{print \$2}')

if [[ -n "\$SENT_ID" ]]; then
    echo "\$LATEST_ID" > "\$LAST_REPLIED_FILE"
    echo "\$CYCLE" > "\$CYCLE_FILE"
    log "OK · cycle \$CYCLE · sent \$SENT_ID · \${#PARAGRAPH}c · \$CLABEL"
else
    log "FAIL · murmur send: \$(echo "\$SEND_OUT" | tail -2)"
fi
WRITER_EOF

elif [[ "$BRIDGE_TYPE" == "comms" ]]; then
    # Comms-bridge writer — just forwards new messages to Telegram (or no-op for now)
    cat > "$WRITER_SH" <<WRITER_EOF
#!/usr/bin/env bash
# ${IDENTITY_NAME,,}-bridge-writer.sh — generated by spawn-murmur-bridge.sh
# Comms-bridge: reads peer messages, forwards to local sink (Telegram/log).
# Customize the FORWARD section for your relay target.

set -uo pipefail

PEER="${PEER_ID:-PLACEHOLDER_FILL_WHEN_KNOWN}"
MURMUR_HOME="$MURMUR_HOME"
EXPECTED_ID="$MY_ID"
STATE_DIR="$STATE_DIR"
LOG="\$HOME/Library/Logs/${IDENTITY_NAME,,}-bridge.out.log"

MURMUR=/opt/homebrew/bin/murmur

ts() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
log() { echo "[\$(ts)] \$*" >> "\$LOG"; }

ME=\$(HOME="\$MURMUR_HOME" "\$MURMUR" me 2>/dev/null | awk '/^ID:/{print \$2}')
[[ "\$ME" != "\$EXPECTED_ID" ]] && { log "wrong identity"; exit 0; }
[[ "\$PEER" == "PLACEHOLDER"* ]] && { log "peer-id not set"; exit 0; }

log "tick"
HOME="\$MURMUR_HOME" "\$MURMUR" sync --with "\$PEER" --timeout 5000 >/dev/null 2>&1
# TODO: parse new messages from sync output and forward to Telegram bot or webhook.
# See main murmur-bridge.py for forward pattern.
WRITER_EOF
fi

chmod +x "$WRITER_SH"
ok "writer script: $WRITER_SH"

# LaunchAgent plist
PLIST="$HOME/Library/LaunchAgents/com.alex.${IDENTITY_NAME,,}-bridge.plist"
cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>com.alex.${IDENTITY_NAME,,}-bridge</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$WRITER_SH</string>
    </array>
    <key>StartInterval</key><integer>$INTERVAL</integer>
    <key>RunAtLoad</key><false/>
    <key>StandardOutPath</key><string>$HOME/Library/Logs/${IDENTITY_NAME,,}-bridge.out.log</string>
    <key>StandardErrorPath</key><string>$HOME/Library/Logs/${IDENTITY_NAME,,}-bridge.err.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
        <key>HOME</key><string>$HOME</string>
        <key>MURMUR_HOME</key><string>$MURMUR_HOME</string>
    </dict>
</dict>
</plist>
PLIST_EOF
ok "LaunchAgent plist: $PLIST"

# ─── 4. dashboard integration (optional) ───
hdr "Phase 4 · dashboard integration"
ask "Register this peer in share-render.py PEERS dict? (y/N)"
read -r REG_ANS
if [[ "$REG_ANS" =~ ^[Yy]$ ]] && [[ -n "$PEER_ID" ]]; then
    SHARE_RENDER="$HOME/bin/share-render.py"
    if [[ -f "$SHARE_RENDER" ]] && ! grep -q "$PEER_ID" "$SHARE_RENDER"; then
        # Insert before closing brace of PEERS dict
        note "patching $SHARE_RENDER"
        warn "edit by hand — add to PEERS dict:  \"$IDENTITY_NAME\": \"$PEER_ID\","
    fi
fi

# ─── 5. launch + acceptance ───
hdr "Phase 5 · launch"
ask "Load LaunchAgent now? (Y/n)"
read -r LOAD_ANS
if [[ ! "$LOAD_ANS" =~ ^[Nn]$ ]]; then
    launchctl load "$PLIST" 2>&1 | sed 's/^/  /'
    sleep 2
    if launchctl list | grep -q "${IDENTITY_NAME,,}-bridge"; then
        ok "LaunchAgent loaded"
    else
        warn "LaunchAgent did not appear in list — check error log"
    fi
fi

# ─── summary ───
hdr "✓ spawn complete"
cat <<SUMMARY

  ${BOLD}identity${INK}        $IDENTITY_NAME
  ${BOLD}your peer-id${INK}    $MY_ID
  ${BOLD}talking to${INK}      $PEER_NAME (${PEER_ID:-<not set>})
  ${BOLD}bridge type${INK}     $BRIDGE_TYPE
  ${BOLD}cadence${INK}         every ${INTERVAL}s

  ${BOLD}files generated${INK}
    · MURMUR_HOME           $MURMUR_HOME
    · writer.sh             $WRITER_SH
    · LaunchAgent plist     $PLIST
    · state dir             $STATE_DIR

  ${BOLD}next steps${INK}
    1. If peer-id was empty, edit PEER= line in $WRITER_SH
    2. Share YOUR peer-id with $PEER_NAME:  $MY_ID
    3. Watch log:  tail -f $HOME/Library/Logs/${IDENTITY_NAME,,}-bridge.out.log
    4. (Optional) Add this peer to share-render.py PEERS dict for dashboard visibility
    5. (Optional) Test send:  HOME=$MURMUR_HOME murmur send --to <peer-id> --message "test"

  ${BOLD}rollback${INK}
    launchctl unload $PLIST
    rm $PLIST $WRITER_SH
    rm -rf $MURMUR_HOME $STATE_DIR

SUMMARY
